import initFuncioanmento from "./modules/funcionamento.js";
import initFetchAnimais from "./modules/fetch-animais.js";
import SmoothScroll from "./modules/smooth-scroll.js";
import initDropdownMenu from "./modules/dropdown-menu.js";
import initFetchBitcoin from "./modules/fetch-bitcoin.js";
import initAnimaScroll from "./modules/anima-scroll.js";
import initMenuMobile from "./modules/menu-mobile.js";
import initAccordion from "./modules/accordion.js";
import initTooltip from "./modules/tooltip.js";
import initTabNav from "./modules/tabnav.js";
import initModal from "./modules/modal.js";

initFuncioanmento();
initFetchAnimais();
const smoothScroll = new SmoothScroll("[data-menu='suave'] a[href^='#']");
smoothScroll.init();
initDropdownMenu();
initFetchBitcoin();
initAnimaScroll();
initMenuMobile();
initAccordion();
initTooltip();
initTabNav();
initModal();
