import initFuncioanmento from "./modules/funcionamento.js";
import initSmoothScroll from "./modules/smooth-scroll.js";
import initDropdownMenu from "./modules/dropdown-menu.js";
import initAnimaNumeros from "./modules/anima-numeros.js";
import initAnimaScroll from "./modules/anima-scroll.js";
import initMenuMobile from "./modules/menuMobile.js";
import initAccordion from "./modules/accordion.js";
import initTooltip from "./modules/tooltip.js";
import initTabNav from "./modules/tabnav.js";
import initModal from "./modules/modal.js";

initFuncioanmento();
initSmoothScroll();
initDropdownMenu();
initAnimaNumeros();
initAnimaScroll();
initMenuMobile();
initAccordion();
initTooltip();
initTabNav();
initModal();
